//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public string Product { get; set; }
        public string Color { get; set; }
        public decimal ListPrice { get; set; }
        public string Category { get; set; }
    }
}
